### ISSUE TITLE
Fatal error. System.AccessViolationException when trying to dispose video stream

### ISSUE THREAD

**Issue by ggolda** [radek-k/FFMediaToolkit#114]
Error with library version 4.4.0, happens when I try to dispose a video stream:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at FFMediaToolkit.Decoding.Internal.Decoder.DiscardBufferedData()
   at FFMediaToolkit.Decoding.MediaStream.Dispose()
   at FFMediaToolkit.Decoding.VideoStream.Dispose()
```
Video stream is created using code sample below:
```c#
          MediaOptions options = new MediaOptions()
          {
              StreamsToLoad = MediaMode.Video,
              VideoPixelFormat = ImagePixelFormat.Rgba32,
          };

          _file = MediaFile.Open(filePath, options);
          if (!_file.HasVideo)
          {
              throw new Exception($"Can't create video resource. Source file of resource {id} doesn't have video stream.");
          }

          _videoStream = _file.Video;
```

Works fine with version 4.1.1

**Comment by radek-k** [comment]
Fixed in v4.4.1

**Comment by ggolda** [comment]
Thanks!

**Comment by tghanem** [comment]
Not sure if it's related to this thread but I got it when disposing the `MediaOutput` object in the latest version (i.e., **4.4.1**). 

It happens rarely, so it's very hard to repro and capture more information but I have a screenshot.

![AccessViolationOnDispose](https://user-images.githubusercontent.com/19247021/170933084-d5b378e7-a196-48b9-b5b8-1a9019d5d7c9.png)
