### ISSUE TITLE
System.DllNotFoundException: Cannot load FFmpeg libraries

### ISSUE THREAD

**Issue by sparrowhawk26** [radek-k/FFMediaToolkit#136]
Hi,

I am using FFMedialTookKit 4.5.1 with .net core 6.0 on linux ubuntu official asp.net microsoft image **mcr.microsoft.com/dotnet/aspnet:6.0-focal**

I got and exception _System.DllNotFoundException: Cannot load FFmpeg libraries_ 
no matter which path i set in `FFmpegLoader.FFmpegPath = Configuration.GetValue<string>("ffmpeg");`

when i attach a bash to my container i can check that ffmpeg is correctly installed at /usr/bin
i tried all paths /usr/bin /usr/share/ffmpeg /usr/lib  /usr/lib/x86_64-linux-gnu

i also run 
```
FFmpeg.Loader.FFmpegLoader.SearchSystem();
FFmpeg.Loader.FFmpegLoader.SearchApplication(); 
```

i got the same error (the found path is /usr/lib/x86_64-linux-gnu)

the full stacktrace :
```
System.Exception: Failed to open the media stream
       ---> System.DllNotFoundException: Cannot load FFmpeg libraries from /usr/lib/x86_64-linux-gnu directory.
      Required FFmpeg version: 6.x (shared build)
      Make sure the "Build"Prefer 32-bit" option in the project settings is turned off.
      For more information please see https://github.com/radek-k/FFMediaToolkit#setup
       ---> System.NotSupportedException: Specified method is not supported.
         at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_1162()
         at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_452()
         at FFmpeg.AutoGen.ffmpeg.av_version_info()
         at FFMediaToolkit.FFmpegLoader.LoadFFmpeg()
         --- End of inner exception stack trace ---
         at FFMediaToolkit.FFmpegLoader.HandleLibraryLoadError(Exception exception)
         at FFMediaToolkit.FFmpegLoader.LoadFFmpeg()
         at FFMediaToolkit.Decoding.Internal.InputContainer.MakeContext(String url, MediaOptions options, AVFormatContextDelegate contextDelegate)
         at FFMediaToolkit.Decoding.Internal.InputContainer.MakeContainer(Stream input, MediaOptions options)
         at FFMediaToolkit.Decoding.Internal.InputContainer.LoadStream(Stream stream, MediaOptions options)
         at FFMediaToolkit.Decoding.MediaFile.Open(Stream stream, MediaOptions options)
         --- End of inner exception stack trace ---
         at FFMediaToolkit.Decoding.MediaFile.Open(Stream stream, MediaOptions options)
         at FFMediaToolkit.Decoding.MediaFile.Open(Stream stream)
```

I don't know what to do 

Thanks for your help

**Comment by curtmantle** [comment]
Hello, 

I ran into the exact same issue and could not get it to work with the latest version of FFmpeg. The solution was to get the shared libraries of an older version of FFmpeg and place this in the  /usr/lib/x86_64-linux-gnu folder.

The one I got was from here:

https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-07-31-12-50

And the specific download was: ffmpeg-n6.0-32-gd4a7a6e7fa-linux64-gpl-shared-6.0.tar.xz

This worked for me so it seems that the nuget package is not compatible with the latest version.

Hope this helps.

**Comment by pachojavier23** [comment]
Hello,

Currently I have the same issue, and even applying the suggestion by @curtmantle , it doesn't seem to work.

I've put all files and folders on ffmpeg-n6.0-32-gd4a7a6e7fa-linux64-gpl-shared-6.0.tar inside /usr/lib/x86_64-linux-gnu/ffmpeg

I'm registering the ffmpeg folder like this:
` private static void LoadFFMpeg()
 {
     string path = Path.Combine("/", "usr", "lib", "x86_64-linux-gnu", "ffmpeg", "bin");

         FFmpegLoader.FFmpegPath = path;
 }`

but I'm getting the following error when FFMediaToolkit registers the binaries: 

```
Specified method is not supported. --    at FFmpeg.AutoGen.DynamicallyLoadedBindings.<>c.<Initialize>b__2_1162()
   at FFmpeg.AutoGen.ffmpeg.av_version_info()
   at FFMediaToolkit.FFmpegLoader.LoadFFmpeg()
```

This project is made in .netcore 8 and is deployed in an isolated azure function on linux64, which uses Debian 

Locally on windows it works fine with the dll files.

**Comment by moon6969** [comment]
I struggled with DLLs not found on Windows.
Fixed by using [FFMediaToolkit v4.5.1](https://github.com/radek-k/FFMediaToolkit/releases/tag/v4.5.1)  rather than Master, and using ffmpeg-n6.0-32-gd4a7a6e7fa-win64-gpl-shared-6.0.zip from https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-07-31-12-50/

**Comment by jekakmail** [comment]
> I struggled with DLLs not found on Windows. Fixed by using [FFMediaToolkit v4.5.1](https://github.com/radek-k/FFMediaToolkit/releases/tag/v4.5.1) rather than Master, and using ffmpeg-n6.0-32-gd4a7a6e7fa-win64-gpl-shared-6.0.zip from https://github.com/BtbN/FFmpeg-Builds/releases/tag/autobuild-2023-07-31-12-50
> 
> Edit: Further testing shows v4.5.1 works up to ffmpeg-n6.1.1

I faced the same problem with FFMediaToolkit 4.5.1
On win10 it would not load with the error:
```
“Cannot load FFmpeg libraries from ....FFmpegConverter\ directory. Required FFmpeg version: 6.x (shared build)
Make sure the 'Build Prefer 32-bit' option in the project settings is turned off.
For more information please see https://github.com/radek-k/FFMediaToolkit#setup”
```

After your comment I started checking ffmpeg-win64-lgpl-shared versions and I got ffmpeg-n6.1-latest-win64-lgpl-shared-6.1.zip (Latest Auto-Build (2025-03-25 13:03)).
